app_name: Menelao

database:
  user: app_user
  host: db
  port: 5432
  db: backend

migrator:
  user: migrator_user
  host: db
  port: 5432
  db: backend

auth:
  bootstrap_admin_email: admin@admin.co
  dev_auto_login_email: admin@admin.co

frontend:
  enabled: true
  components_dir: src/frontend/components
  static_dir: src/frontend/static
