"""add rag operation state

Revision ID: 011b72a9d4a2
Revises: ca6c2ee48b08
Create Date: 2026-08-19 19:00:11.719153

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "011b72a9d4a2"
down_revision = "ca6c2ee48b08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rags", sa.Column("conversion_task_id", sa.UUID(), nullable=True))
    op.add_column("rags", sa.Column("indexing_task_id", sa.UUID(), nullable=True))
    op.add_column("rags", sa.Column("index_file_id", sa.UUID(), nullable=True))
    op.create_unique_constraint(
        op.f("uq_rags_index_file_id"), "rags", ["index_file_id"]
    )
    op.create_foreign_key(
        op.f("fk_rags_index_file_id_files"),
        "rags",
        "files",
        ["index_file_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_rags_indexing_task_id_tasks"),
        "rags",
        "tasks",
        ["indexing_task_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_rags_conversion_task_id_tasks"),
        "rags",
        "tasks",
        ["conversion_task_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_rags_conversion_task_id_tasks"), "rags", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_rags_indexing_task_id_tasks"), "rags", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_rags_index_file_id_files"), "rags", type_="foreignkey")
    op.drop_constraint(op.f("uq_rags_index_file_id"), "rags", type_="unique")
    op.drop_column("rags", "index_file_id")
    op.drop_column("rags", "indexing_task_id")
    op.drop_column("rags", "conversion_task_id")
    # ### end Alembic commands ###
