"""add file mime type

Revision ID: 13c92ef09af6
Revises: 6d917d5c1749
Create Date: 2026-08-18 18:50:11.599115

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13c92ef09af6"
down_revision = "6d917d5c1749"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("mime_type", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "mime_type")
    # ### end Alembic commands ###
