"""add knowledge base ownership and sharing

Revision ID: 6d917d5c1749
Revises: 84d8b69b9518
Create Date: 2026-08-18 15:22:11.908362

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d917d5c1749"
down_revision = "84d8b69b9518"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_base_shared_users",
        sa.Column("knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f(
                "fk_knowledge_base_shared_users_knowledge_base_id_knowledge_bases"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_knowledge_base_shared_users_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "knowledge_base_id", "user_id", name=op.f("pk_knowledge_base_shared_users")
        ),
    )
    op.add_column(
        "knowledge_bases", sa.Column("created_by_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_knowledge_bases_created_by_id_users"),
        "knowledge_bases",
        "users",
        ["created_by_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_knowledge_bases_created_by_id_users"),
        "knowledge_bases",
        type_="foreignkey",
    )
    op.drop_column("knowledge_bases", "created_by_id")
    op.drop_table("knowledge_base_shared_users")
    # ### end Alembic commands ###
