"""add mcp audit models

Revision ID: 80d8ee3be5d7
Revises: 011b72a9d4a2
Create Date: 2026-08-20 11:30:34.862059

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80d8ee3be5d7"
down_revision = "011b72a9d4a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_users",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_users")),
        sa.UniqueConstraint(
            "provider", "provider_subject", name="uq_mcp_user_provider_subject"
        ),
    )
    op.create_table(
        "mcp_sessions",
        sa.Column("mcp_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mcp_user_id"],
            ["mcp_users.id"],
            name=op.f("fk_mcp_sessions_mcp_user_id_mcp_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_sessions")),
    )
    op.create_table(
        "mcp_tool_calls",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "tool",
            sa.Enum("LIST_RAGS", "SEARCH", "FETCH_FILE", name="mcp_tool_name"),
            nullable=False,
        ),
        sa.Column("rag_id", sa.UUID(), nullable=True),
        sa.Column("source_file_id", sa.UUID(), nullable=True),
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rag_id"],
            ["rags.id"],
            name=op.f("fk_mcp_tool_calls_rag_id_rags"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["mcp_sessions.id"],
            name=op.f("fk_mcp_tool_calls_session_id_mcp_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["files.id"],
            name=op.f("fk_mcp_tool_calls_source_file_id_files"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_tool_calls")),
    )
    op.create_index(
        "ix_mcp_tool_calls_session_created_at",
        "mcp_tool_calls",
        ["session_id", "created_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mcp_tool_calls_session_created_at", table_name="mcp_tool_calls")
    op.drop_table("mcp_tool_calls")
    op.drop_table("mcp_sessions")
    op.drop_table("mcp_users")
    # ### end Alembic commands ###
