"""add rag models

Revision ID: ca6c2ee48b08
Revises: 13c92ef09af6
Create Date: 2026-08-19 18:45:43.866277

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca6c2ee48b08"
down_revision = "13c92ef09af6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rags",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("source_knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("converted_knowledge_base_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["converted_knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_rags_converted_knowledge_base_id_knowledge_bases"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_rags_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["source_knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_rags_source_knowledge_base_id_knowledge_bases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rags")),
        sa.UniqueConstraint(
            "converted_knowledge_base_id",
            name=op.f("uq_rags_converted_knowledge_base_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rags")
    # ### end Alembic commands ###
